### PR TITLE
W-10736467-survey-banner-updates-kt

### PR DESCRIPTION
**Pull request by kevintroller**
W-10736467 Updates for new banner redesign

**Enhancements**

- Created new vertical banner that is positioned below the right TOC in the docs site.
- Updated wording, styling, colors and new icons for the banner.
- Updated initial horizontal banner (at the bottom of the page).

I need help with the following before merging into production:

- I'm having issues when serving the correct banner (vertical vs horizontal) for small size windows. I used the CSS property `display: none` for `--lg` and `--xl` windows for the horizontal banner but that removes the Muley icon in the new vertical banner.
 See the expected correct behavior:
 
Screen Shot 2022-03-03 at 9 42 23 AM

- Check that the new vertical banner appears on the Connectors pages, for example, Salesforce Connector.

### CODE REVIEW

**Comment by cheungaryk** [comment]
@kevintroller the reason why your Muley icon on the vertical banner disappears is because it shared the same HTML ID as the bottom Muley icon. I changed the IDs in f843713 which no longer hides the icons.

**Comment by cheungaryk** [comment]
I did some more clean up on the CSS and pushed it to a separate branch: https://github.com/mulesoft/docs-site-ui/compare/W-10736467-survey-banner-updates-kt...w-10736467-survey-banner-updates-gc?expand=1. Specifically, I combined the CSS for both so that it's easier to maintain. Screenshots below:

Screen Shot 2022-03-03 at 5 04 19 PM

Screen Shot 2022-03-03 at 5 04 26 PM

**Comment by cheungaryk** [comment]
I merged the branch [w-10736467-survey-banner-updates-gc](https://github.com/mulesoft/docs-site-ui/tree/w-10736467-survey-banner-updates-gc) since Kevin said it "looks good" via Slack DM.

Also I updated a button CSS in 55610bd. In docs.mulesoft.com, if you click the survey button (which opens userzoom in a new tab) and then return back to the page, the text disappears until you click away from the button. The new CSS should remove the color change when focusing, so it will revert to white color.

**Review by cheungaryk — APPROVED** [review]

**Comment by cheungaryk** [comment]
@sanderson-sfdc please review and approve. I am 1 of the contributors in the PR so my approval isn't sufficient.

**Review by cheungaryk — APPROVED** [review]

**Comment by kevintroller** [comment]
Hi @cheungaryk I just saw that the currently live banner shows as duplicated in Connectors pages, see at the bottom of this page https://docs.mulesoft.com/http-connector/1.6/http-request-ref (Also adding a screenshot for reference). I'm adding this comment so the new banner design does not show as duplicated as well.
Screen Shot 2022-03-09 at 2 57 49 PM

**Review by sanderson-sfdc — APPROVED** [review]
Sorry for the delay!  LGTM!

**Pull request merged**
