### PR TITLE
restore exclusion logic in nav

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Review by sanderson-sfdc — APPROVED** [review]

**Comment by sanderson-sfdc** [comment]
@cheungaryk - can you take a look at this?  I've verified it resolves the problem, but you've been doing a lot of work on this project and I don't want to mess that up.

**Comment by cheungaryk** [comment]
> @cheungaryk - can you take a look at this? I've verified it resolves the problem, but you've been doing a lot of work on this project and I don't want to mess that up.

I validated locally as well. LGTM

**Comment by sanderson-sfdc** [comment]
@mojavelinux - thanks for the fix.  It looks like you need to sign the CLA for us to be able to merge it.  If you don't want to do that, we'll update the code in a different PR.

**Comment by mojavelinux** [comment]
You can update the code in a separate PR. I just submitted a PR since it's the easy way to communicate which lines need to change.

**Comment by cheungaryk** [comment]
Changes in this PR have all been merged in #184. Closing this

**Pull request closed without merging**
